# Generated by Django 5.2.1 on 2025-06-08 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('crp_accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_accounts_payable_control',
            field=models.ForeignKey(blank=True, help_text='Primary A/P control. Liability type, control for Suppliers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default A/P Control Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_accounts_receivable_control',
            field=models.ForeignKey(blank=True, help_text='Primary A/R control. Asset type, control for Customers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default A/R Control Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_bank_account_for_payments_made',
            field=models.ForeignKey(blank=True, help_text='Default bank/cash for AP payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Bank Account for Payments Made'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_purchase_expense_account',
            field=models.ForeignKey(blank=True, help_text='Default expense/asset for purchases. Expense or Asset type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Purchase/Expense Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_purchase_tax_asset_account',
            field=models.ForeignKey(blank=True, help_text='Asset for recoverable purchase tax.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Purchase Tax Asset Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_retained_earnings_account',
            field=models.ForeignKey(blank=True, help_text="Equity account for net income. Must be 'Equity' type.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Retained Earnings Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_sales_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Default revenue for sales. Income type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Sales Revenue Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_sales_tax_payable_account',
            field=models.ForeignKey(blank=True, help_text='Sales tax accrual. Liability type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Sales Tax Payable Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='default_unapplied_customer_cash_account',
            field=models.ForeignKey(blank=True, help_text='Liability for unapplied customer payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Unapplied Customer Cash Account'),
        ),
        migrations.AddField(
            model_name='companyaccountingsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_accounting_settings', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user', 'is_default_for_user'], name='company_com_user_id_5b777a_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user', 'company'], name='company_com_user_id_edc4bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('company', 'user')},
        ),
    ]
