# Generated by Django 5.2.1 on 2025-05-14 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('crp_accounting', '0007_remove_account_coa_co_spc_purpose_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountingSettings',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accounting_settings', serialize=False, to='company.company', verbose_name='Company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_accounts_payable_control', models.ForeignKey(blank=True, help_text='Primary A/P control. Liability type, control for Suppliers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default A/P Control Account')),
                ('default_accounts_receivable_control', models.ForeignKey(blank=True, help_text='Primary A/R control. Asset type, control for Customers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default A/R Control Account')),
                ('default_bank_account_for_payments_made', models.ForeignKey(blank=True, help_text='Default bank/cash for AP payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Bank Account for Payments Made')),
                ('default_purchase_expense_account', models.ForeignKey(blank=True, help_text='Default expense/asset for purchases. Expense or Asset type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Purchase/Expense Account')),
                ('default_purchase_tax_asset_account', models.ForeignKey(blank=True, help_text='Asset for recoverable purchase tax.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Purchase Tax Asset Account')),
                ('default_retained_earnings_account', models.ForeignKey(blank=True, help_text="Equity account for net income. Must be 'Equity' type.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Retained Earnings Account')),
                ('default_sales_revenue_account', models.ForeignKey(blank=True, help_text='Default revenue for sales. Income type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Sales Revenue Account')),
                ('default_sales_tax_payable_account', models.ForeignKey(blank=True, help_text='Sales tax accrual. Liability type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Sales Tax Payable Account')),
                ('default_unapplied_customer_cash_account', models.ForeignKey(blank=True, help_text='Liability for unapplied customer payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crp_accounting.account', verbose_name='Default Unapplied Customer Cash Account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_accounting_settings', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Company Accounting Settings',
                'verbose_name_plural': 'Company Accounting Settings',
            },
        ),
    ]
