# Generated by Django 5.2.1 on 2025-06-04 05:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('crp_accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorpaymentallocation',
            options={'ordering': ['vendor_payment__payment_date', 'vendor_bill__issue_date', 'allocation_date'], 'verbose_name': 'Vendor Payment Allocation', 'verbose_name_plural': 'Vendor Payment Allocations'},
        ),
        migrations.AlterField(
            model_name='historicalparty',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For Customers: Maximum credit amount extended to them. For Suppliers: An internal threshold for the maximum amount owed to them. 0 means no limit is applied.', max_digits=15, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpaymentallocation',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The company this record belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='party',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For Customers: Maximum credit amount extended to them. For Suppliers: An internal threshold for the maximum amount owed to them. 0 means no limit is applied.', max_digits=15, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentallocation',
            name='company',
            field=models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='company.company', verbose_name='Company'),
        ),
    ]
