# Generated by Django 5.2.1 on 2025-05-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0002_customerinvoice_customerpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pl_section',
            field=models.CharField(blank=True, choices=[('REVENUE', 'Revenue'), ('OPENING_STOCK_COGS', 'Opening Stock (COGS)'), ('PURCHASES_COGS', 'Purchases (COGS)'), ('FREIGHT_IN_COGS', 'Freight-In (COGS)'), ('PURCHASE_RETURNS_COGS_ADJ', 'Purchase Returns Adj. (COGS)'), ('PURCHASE_DISCOUNTS_COGS_ADJ', 'Purchase Discounts Adj. (COGS)'), ('CLOSING_STOCK_COGS_ADJ', 'Closing Stock Adj. (COGS)'), ('COGS', 'Cost of Goods Sold (Direct/Perpetual)'), ('OPERATING_EXPENSE', 'Operating Expense'), ('DEPR_AMORT', 'Depreciation & Amortization'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense'), ('TAX_EXPENSE', 'Tax Expense'), ('NONE', 'Not Applicable (Balance Sheet Accounts)')], db_index=True, default='NONE', help_text='Specific section classification for the Profit & Loss statement.', max_length=30, verbose_name='P&L Section'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='pl_section',
            field=models.CharField(blank=True, choices=[('REVENUE', 'Revenue'), ('OPENING_STOCK_COGS', 'Opening Stock (COGS)'), ('PURCHASES_COGS', 'Purchases (COGS)'), ('FREIGHT_IN_COGS', 'Freight-In (COGS)'), ('PURCHASE_RETURNS_COGS_ADJ', 'Purchase Returns Adj. (COGS)'), ('PURCHASE_DISCOUNTS_COGS_ADJ', 'Purchase Discounts Adj. (COGS)'), ('CLOSING_STOCK_COGS_ADJ', 'Closing Stock Adj. (COGS)'), ('COGS', 'Cost of Goods Sold (Direct/Perpetual)'), ('OPERATING_EXPENSE', 'Operating Expense'), ('DEPR_AMORT', 'Depreciation & Amortization'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense'), ('TAX_EXPENSE', 'Tax Expense'), ('NONE', 'Not Applicable (Balance Sheet Accounts)')], db_index=True, default='NONE', help_text='Specific section classification for the Profit & Loss statement.', max_length=30, verbose_name='P&L Section'),
        ),
    ]
