# Generated by Django 5.2.1 on 2025-05-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0004_account_created_by_account_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, editable=False, help_text='The GL voucher created when this invoice was posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_customer_invoice', to='crp_accounting.voucher', verbose_name='Related GL Voucher (Invoice)'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, editable=False, help_text='The GL voucher created when this payment was posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_customer_payment', to='crp_accounting.voucher', verbose_name='Related GL Voucher (Payment)'),
        ),
        migrations.AddField(
            model_name='historicalcustomerinvoice',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='The GL voucher created when this invoice was posted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher', verbose_name='Related GL Voucher (Invoice)'),
        ),
        migrations.AddField(
            model_name='historicalcustomerpayment',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='The GL voucher created when this payment was posted.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher', verbose_name='Related GL Voucher (Payment)'),
        ),
    ]
