# Generated by Django 5.2.1 on 2025-05-14 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('crp_accounting', '0005_customerinvoice_related_gl_voucher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='special_purpose_code',
            field=models.CharField(blank=True, db_index=True, help_text="A unique code for system-referenced accounts like 'ACCOUNTS_RECEIVABLE', 'SALES_TAX_PAYABLE'.", max_length=50, null=True, verbose_name='Special Purpose Code'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='special_purpose_code',
            field=models.CharField(blank=True, db_index=True, help_text="A unique code for system-referenced accounts like 'ACCOUNTS_RECEIVABLE', 'SALES_TAX_PAYABLE'.", max_length=50, null=True, verbose_name='Special Purpose Code'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(condition=models.Q(('special_purpose_code__isnull', False)), fields=['company', 'special_purpose_code'], name='coa_co_spc_purpose_idx'),
        ),
    ]
