# Generated by Django 5.2.1 on 2025-05-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0006_account_special_purpose_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='coa_co_spc_purpose_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='special_purpose_code',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='special_purpose_code',
        ),
    ]
