# Generated by Django 5.2.1 on 2025-05-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0008_creditmemo_creditmemoline_historicalcreditmemo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditmemoline',
            name='credit_memo',
        ),
        migrations.RemoveField(
            model_name='creditmemoline',
            name='account_to_debit',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='original_invoice',
        ),
        migrations.RemoveField(
            model_name='historicalcreditmemo',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CreditMemo',
        ),
        migrations.DeleteModel(
            name='CreditMemoLine',
        ),
        migrations.DeleteModel(
            name='HistoricalCreditMemo',
        ),
    ]
