# Generated by Django 5.2.1 on 2025-05-15 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0009_remove_creditmemoline_credit_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_customer_invoice', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_customer_payment', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerinvoice',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerpayment',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='historicalinvoicesequence',
            name='current_period_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='Current Period Key'),
        ),
        migrations.AlterField(
            model_name='historicalinvoicesequence',
            name='padding_digits',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits'),
        ),
        migrations.AlterField(
            model_name='historicalinvoicesequence',
            name='period_format_for_reset',
            field=models.CharField(blank=True, help_text="Strftime format (e.g., '%Y' yearly, '%Y%m' monthly). Blank for continuous.", max_length=10, null=True, verbose_name='Period Format for Reset'),
        ),
        migrations.AlterField(
            model_name='historicalinvoicesequence',
            name='prefix',
            field=models.CharField(blank=True, default='INV-', max_length=20, verbose_name='Invoice Prefix'),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='current_period_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='Current Period Key'),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='padding_digits',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits'),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='period_format_for_reset',
            field=models.CharField(blank=True, help_text="Strftime format (e.g., '%Y' yearly, '%Y%m' monthly). Blank for continuous.", max_length=10, null=True, verbose_name='Period Format for Reset'),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='prefix',
            field=models.CharField(blank=True, default='INV-', max_length=20, verbose_name='Invoice Prefix'),
        ),
    ]
