# Generated by Django 5.2.1 on 2025-05-15 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyaccountingsettings'),
        ('crp_accounting', '0011_historicalbillsequence_historicalvendorbill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentSequence',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('prefix', models.CharField(default='VPAY-', max_length=20, verbose_name='Prefix')),
                ('period_format_for_reset', models.CharField(blank=True, help_text="Strftime format (e.g., '%Y'). Blank for continuous.", max_length=10, null=True, verbose_name='Period Format for Reset')),
                ('current_period_key', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='Current Period Key')),
                ('padding_digits', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Current Number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Vendor Payment Sequence',
                'verbose_name_plural': 'historical Vendor Payment Sequences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentSequence',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('prefix', models.CharField(default='VPAY-', max_length=20, verbose_name='Prefix')),
                ('period_format_for_reset', models.CharField(blank=True, help_text="Strftime format (e.g., '%Y'). Blank for continuous.", max_length=10, null=True, verbose_name='Period Format for Reset')),
                ('current_period_key', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='Current Period Key')),
                ('padding_digits', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Current Number')),
            ],
            options={
                'verbose_name': 'Vendor Payment Sequence',
                'verbose_name_plural': 'Vendor Payment Sequences',
                'ordering': ['company__name', 'prefix', '-current_period_key'],
            },
        ),
        migrations.AlterModelOptions(
            name='billsequence',
            options={'ordering': ['company__name', 'prefix', '-current_period_key'], 'verbose_name': 'Vendor Bill Sequence', 'verbose_name_plural': 'Vendor Bill Sequences'},
        ),
        migrations.AlterModelOptions(
            name='historicalbillsequence',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vendor Bill Sequence', 'verbose_name_plural': 'historical Vendor Bill Sequences'},
        ),
        migrations.AlterUniqueTogether(
            name='billsequence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbill',
            unique_together={('company', 'supplier', 'supplier_bill_reference')},
        ),
        migrations.AddField(
            model_name='billsequence',
            name='current_period_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Internal: Stores the formatted period string (e.g., '2024' or '202405') if periodic reset is used. This key, along with company and prefix, defines a unique sequence counter.", max_length=20, null=True, verbose_name='Current Period Key'),
        ),
        migrations.AddField(
            model_name='billsequence',
            name='period_format_for_reset',
            field=models.CharField(blank=True, help_text="Optional strftime format for period-based reset (e.g., '%Y' for yearly, '%Y%m' for monthly). Leave blank for continuous numbering across all periods for this prefix.", max_length=10, null=True, verbose_name='Period Format for Reset'),
        ),
        migrations.AddField(
            model_name='historicalbillsequence',
            name='current_period_key',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text="Internal: Stores the formatted period string (e.g., '2024' or '202405') if periodic reset is used. This key, along with company and prefix, defines a unique sequence counter.", max_length=20, null=True, verbose_name='Current Period Key'),
        ),
        migrations.AddField(
            model_name='historicalbillsequence',
            name='period_format_for_reset',
            field=models.CharField(blank=True, help_text="Optional strftime format for period-based reset (e.g., '%Y' for yearly, '%Y%m' for monthly). Leave blank for continuous numbering across all periods for this prefix.", max_length=10, null=True, verbose_name='Period Format for Reset'),
        ),
        migrations.AddField(
            model_name='historicalvendorbill',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='historicalvendorbill',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_bills', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines_as_expense', to='crp_accounting.account', verbose_name='Expense/Asset Account'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='Line Sequence'),
        ),
        migrations.AlterField(
            model_name='billsequence',
            name='current_number',
            field=models.PositiveIntegerField(default=0, help_text='The last sequential number issued for the current company, prefix, and period_key combination.', verbose_name='Current Number'),
        ),
        migrations.AlterField(
            model_name='billsequence',
            name='padding_digits',
            field=models.PositiveSmallIntegerField(default=5, help_text="Total number of digits for the sequential numeric part, including leading zeros (e.g., 5 for '00001'). Minimum 1.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits'),
        ),
        migrations.AlterField(
            model_name='billsequence',
            name='prefix',
            field=models.CharField(blank=True, default='BILL-', help_text="Static prefix for generated bill numbers (e.g., 'BILL-', 'SUP-INV-').", max_length=20, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved for Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed / Cleared'), ('FAILED', 'Failed'), ('VOID', 'Void'), ('UNAPPLIED', 'Unapplied'), ('PARTIALLY_APPLIED', 'Partially Applied'), ('APPLIED', 'Applied'), ('PARTIALLY_PAID', 'PARTIALLY PAID')], db_index=True, default='UNAPPLIED', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global rate, or select company for tenant-specific rate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='company.company', verbose_name='Company (Optional)'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, help_text="1 unit of 'From Currency' = 'Rate' units of 'To Currency'.", max_digits=20, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, help_text='Optional: Source of this exchange rate.', max_length=100, null=True, verbose_name='Rate Source (Optional)'),
        ),
        migrations.AlterField(
            model_name='historicalbillline',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalbillline',
            name='expense_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.account', verbose_name='Expense/Asset Account'),
        ),
        migrations.AlterField(
            model_name='historicalbillline',
            name='sequence',
            field=models.PositiveIntegerField(default=0, verbose_name='Line Sequence'),
        ),
        migrations.AlterField(
            model_name='historicalbillsequence',
            name='current_number',
            field=models.PositiveIntegerField(default=0, help_text='The last sequential number issued for the current company, prefix, and period_key combination.', verbose_name='Current Number'),
        ),
        migrations.AlterField(
            model_name='historicalbillsequence',
            name='padding_digits',
            field=models.PositiveSmallIntegerField(default=5, help_text="Total number of digits for the sequential numeric part, including leading zeros (e.g., 5 for '00001'). Minimum 1.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Padding Digits'),
        ),
        migrations.AlterField(
            model_name='historicalbillsequence',
            name='prefix',
            field=models.CharField(blank=True, default='BILL-', help_text="Static prefix for generated bill numbers (e.g., 'BILL-', 'SUP-INV-').", max_length=20, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved for Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed / Cleared'), ('FAILED', 'Failed'), ('VOID', 'Void'), ('UNAPPLIED', 'Unapplied'), ('PARTIALLY_APPLIED', 'Partially Applied'), ('APPLIED', 'Applied'), ('PARTIALLY_PAID', 'PARTIALLY PAID')], db_index=True, default='UNAPPLIED', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave blank for global rate, or select company for tenant-specific rate.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company (Optional)'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, help_text="1 unit of 'From Currency' = 'Rate' units of 'To Currency'.", max_digits=20, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='historicalexchangerate',
            name='source',
            field=models.CharField(blank=True, help_text='Optional: Source of this exchange rate.', max_length=100, null=True, verbose_name='Rate Source (Optional)'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Amount Due'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='bill_number',
            field=models.CharField(blank=True, db_index=True, help_text='System generated unique bill number.', max_length=50, null=True, verbose_name='Bill Number (System)'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('OTHER', 'Other')], max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Subtotal (Excl. Tax)'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'party_type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.party', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='supplier_bill_reference',
            field=models.CharField(blank=True, db_index=True, help_text="Supplier's own invoice/bill number.", max_length=100, null=True, verbose_name='Supplier Bill Reference'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='historicalvendorbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Total Amount (Incl. Tax)'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Allocated Amount'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('OTHER', 'Other')], max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card (Company)'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='payment_number',
            field=models.CharField(blank=True, db_index=True, help_text='System generated or external reference.', max_length=50, null=True, verbose_name='Payment Number'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='reference_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference (e.g., Check #)'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='related_gl_voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.voucher'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED_PAYMENT', 'Approved for Payment'), ('PAID_COMPLETED', 'Paid / Completed'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'party_type': 'SUPPLIER'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crp_accounting.party'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpayment',
            name='unallocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Unallocated Amount'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpaymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Allocated Amount'),
        ),
        migrations.AlterField(
            model_name='historicalvendorpaymentallocation',
            name='allocation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Allocation Date'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Amount Due'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='bill_number',
            field=models.CharField(blank=True, db_index=True, help_text='System generated unique bill number.', max_length=50, null=True, verbose_name='Bill Number (System)'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('OTHER', 'Other')], max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vendor_bill', to='crp_accounting.voucher', verbose_name='Related GL Voucher'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Subtotal (Excl. Tax)'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'party_type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='bills_as_supplier', to='crp_accounting.party', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='supplier_bill_reference',
            field=models.CharField(blank=True, db_index=True, help_text="Supplier's own invoice/bill number.", max_length=100, null=True, verbose_name='Supplier Bill Reference'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Total Amount (Incl. Tax)'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Allocated Amount'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan Renminbi'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NZD', 'New Zealand Dollar'), ('OTHER', 'Other')], max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_account',
            field=models.ForeignKey(limit_choices_to=models.Q(('account_type', 'ASSET')), on_delete=django.db.models.deletion.PROTECT, related_name='payments_made_from_account', to='crp_accounting.account', verbose_name='Paid From Account (Bank/Cash)'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_CARD', 'Credit Card (Company)'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=30, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_number',
            field=models.CharField(blank=True, db_index=True, help_text='System generated or external reference.', max_length=50, null=True, verbose_name='Payment Number'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='reference_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Reference (e.g., Check #)'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='related_gl_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_vendor_payment', to='crp_accounting.voucher'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED_PAYMENT', 'Approved for Payment'), ('PAID_COMPLETED', 'Paid / Completed'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'party_type': 'SUPPLIER'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments_made_to_supplier', to='crp_accounting.party'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='unallocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, verbose_name='Unallocated Amount'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentallocation',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Allocated Amount'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentallocation',
            name='allocation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Allocation Date'),
        ),
        migrations.AlterUniqueTogether(
            name='billsequence',
            unique_together={('company', 'prefix', 'current_period_key')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorbill',
            unique_together={('company', 'bill_number'), ('company', 'supplier', 'supplier_bill_reference')},
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.CheckConstraint(condition=models.Q(('bill_number__isnull', False), ('status', 'DRAFT'), _connector='OR'), name='non_draft_bill_must_have_number', violation_error_message='Non-draft bills must have a bill number.'),
        ),
        migrations.AddField(
            model_name='historicalpaymentsequence',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The company this record belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='historicalpaymentsequence',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicalpaymentsequence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpaymentsequence',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AddField(
            model_name='paymentsequence',
            name='company',
            field=models.ForeignKey(help_text='The company this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='paymentsequence',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='paymentsequence',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentsequence',
            unique_together={('company', 'prefix', 'current_period_key')},
        ),
    ]
