# Generated by Django 5.2.1 on 2025-05-29 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crp_accounting', '0014_alter_accountgroup_options_alter_voucher_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='allow_direct_posting',
            field=models.BooleanField(default=True, help_text='Can journal entries be posted directly to this account? (Usually False for summary/parent accounts).', verbose_name='Allow Direct Posting'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Denormalized current balance. Updated by system processes (e.g., daily batch job or triggers).', max_digits=20, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='True if this account summarizes a subsidiary ledger (e.g., Accounts Receivable controlling customer balances).', verbose_name='Is Control Account'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='allow_direct_posting',
            field=models.BooleanField(default=True, help_text='Can journal entries be posted directly to this account? (Usually False for summary/parent accounts).', verbose_name='Allow Direct Posting'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Denormalized current balance. Updated by system processes (e.g., daily batch job or triggers).', max_digits=20, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='is_control_account',
            field=models.BooleanField(default=False, help_text='True if this account summarizes a subsidiary ledger (e.g., Accounts Receivable controlling customer balances).', verbose_name='Is Control Account'),
        ),
    ]
